<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/28 20:55:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=myMovies',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
